export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CARD = "DELETE_FROM_CARD";
export const INCREASE_NUMBER_OF_PIECES = "INCREASE_NUMBER_OF_PIECES";
export const DESCREASE_NUMBER_OF_PIECES = "DESCREASE_NUMBER_OF_PIECES";